### ISSUE TITLE
The Discord Bot doesnt start

### ISSUE THREAD

**Issue by HerrFisch** [FQQD/simple-moderation-bot#1]
It says that I need do install disnake, its a very bad bot with bad support

**Comment by FQQD** [comment]
What exactly is your problem? Did you follow the instructions?

**Comment by OhaDerErste** [comment]
> It says that I need do install disnake, its a very bad bot with bad support

I totally agree with you

**Comment by FQQD** [comment]
To install the required disnake package, please do
`pip3 install disnake`
